tasks:
  - name: terraform
    before: |
      source ./bin/generate_terraform_alias
      source ./bin/install_terraform_cli
      source ./bin/generate_tfrc_json
      cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/generate_terraform_alias
      source ./bin/install_aws_cli
  - name: http-server
    before: |
      npm install --global http-server
    command:
      http-server
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform